force-app/main/default/objects/Account/fields/Disqualified__c.field-meta.xml
<CustomField>
    <fullName>Disqualified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies  if an account is qualified or not for loan</description>
    <label>Disqualified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Rule__mdt/Interest_Rule__mdt.object-meta.xml
<CustomObject>
    <label>Interest Rule</label>
    <pluralLabel>Interest Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interest_Rule__mdt/fields/Disqualified__c.field-meta.xml
<CustomField>
    <fullName>Disqualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disqualified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interest_Rule__mdt/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Rule__mdt/fields/Rule_Order__c.field-meta.xml
<CustomField>
    <fullName>Rule_Order__c</fullName>
    <label>Rule Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Rule_Criteria__mdt/Interest_Rule_Criteria__mdt.object-meta.xml
<CustomObject>
    <label>Interest Rule Criteria</label>
    <pluralLabel>Interest Rule Criterias</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interest_Rule_Criteria__mdt/fields/Interest_Rule__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rule__c</fullName>
    <label>Interest Rule</label>
    <referenceTo>Interest_Rule__mdt</referenceTo>
    <relationshipLabel>Interest Rule Criterias</relationshipLabel>
    <relationshipName>Interest_Rule_Criterias</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Interest_Rule_Criteria__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <default>true</default>
                <label>=</label>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterestRateCalculator.cls
public without sharing class InterestRateCalculator {

    public class CalculatorException extends Exception {}
    private static final Double BASE_INTEREST_RATE = 5.0;



    public static void calculate(Account acc) {
        
        //Load rules
        List<Interest_Rule__mdt> rulesList = [select Id, Disqualified__c, Interest_Rate__c, 
                                   (select  Field_Name__c, Operator__c, Value__c 
                                   from Interest_Rule_Criterias__r) 
                                   from Interest_Rule__mdt 
where IsActive__c = true order by Rule_Order__c asc];
        
        Double interestRateOffset = 0;
        Boolean isDisqualifed = false;
        for ( Integer idx=0; !isDisqualifed && idx < rulesList.size(); idx++ ) {
            Interest_Rule__mdt rule = rulesList.get(idx);
            if ( !isDisqualifed && evaluateRule(rule, acc) ) {
                //rule matched
                //apply actions
                isDisqualifed = rule.Disqualified__c;
                if ( rule.Interest_Rate__c != null) {
                    interestRateOffset = interestRateOffset + rule.Interest_Rate__c;
                }
            }
        }
        
        if ( !isDisqualifed ) {
        	acc.Interest_Rate__c = BASE_INTEREST_RATE + interestRateOffset;
            acc.Disqualified__c = false;
        }
        else {
            //TODO: set to 0
            acc.Interest_Rate__c = 0;
            acc.Disqualified__c = true;
        }
        
        
    }
    
    private static Boolean evaluateRule(Interest_Rule__mdt rule, Account acc) {
        
        if ( rule.Interest_Rule_Criterias__r.size() > 0) {
            
            //evaluate criteria
            Boolean criteriaResult = true;
            for ( Interest_Rule_Criteria__mdt criteria : rule.Interest_Rule_Criterias__r) {

                criteriaResult = criteriaResult && evaluateCriteria(criteria, acc);

                if (!criteriaResult) {
                    //criteria evaluated to false
                    return false;
                }

            }

            return criteriaResult;

        }
        else {
 			//not criterias found
            return false;
        }
        
       // return false;
    }
    
    private static Boolean evaluateCriteria(Interest_Rule_Criteria__mdt criteria, Account acc) {
        
        if( criteria.Operator__c == '=') {
            return (String.valueOf(acc.get(criteria.Field_Name__c)) == criteria.Value__c);
        }
        else if (criteria.Operator__c == '>') {
            return Double.valueOf(acc.get(criteria.Field_Name__c)) > Double.valueOf(criteria.Value__c);
        }
        else if (criteria.Operator__c == '>=') {
            return Double.valueOf(acc.get(criteria.Field_Name__c)) >= Double.valueOf(criteria.Value__c);
        }
        else if (criteria.Operator__c == '<') {
            return Double.valueOf(acc.get(criteria.Field_Name__c)) < Double.valueOf(criteria.Value__c);
        }
        else if (criteria.Operator__c == '<=') {
            return Double.valueOf(acc.get(criteria.Field_Name__c)) < Double.valueOf(criteria.Value__c);
        }
        else {
            System.debug('invalid operator');
        }
        
        return false;
    }

}